from src.defs import groups, objects  # noqa: F401

MM_LAYERS = {
    "standard": {"display_name": "Standard Minimap", "filter": None, "subfilter": None},
    "base1": {"display_name": "Base Layer 1", "filter": groups.DECOR, "subfilter": None},
    "base2": {"display_name": "Base Layer 2", "filter": None, "subfilter": None},
    "border": {"display_name": "Border Objects", "filter": groups.BORDER, "subfilter": None},
    "seershuts": {"display_name": "Seer's Huts", "filter": {objects.ID.Seers_Hut}, "subfilter": None},
    # "tents": {"display_name": "Keymaster's Tents", "filter": {objects.ID.Keymasters_Tent}, "subfilter": None},
    # "monoliths1_en": {
    #     "display_name": "One-Way Monolith Entrances",
    #     "filter": {objects.ID.One_Way_MonolithPortal_Entrance},
    #     "subfilter": groups.ONE_WAY_MONOLITHS,
    # },
    # "monoliths1_ex": {
    #     "display_name": "One-Way Monolith Exits",
    #     "filter": {objects.ID.One_Way_MonolithPortal_Exit},
    #     "subfilter": groups.ONE_WAY_MONOLITHS,
    # },
    # "portals1_en": {
    #     "display_name": "One-Way Portal Entrances",
    #     "filter": {objects.ID.One_Way_MonolithPortal_Entrance},
    #     "subfilter": groups.ONE_WAY_PORTALS,
    # },
    # "portals1_ex": {
    #     "display_name": "One-Way Portal Exits",
    #     "filter": {objects.ID.One_Way_MonolithPortal_Exit},
    #     "subfilter": groups.ONE_WAY_PORTALS,
    # },
    # "monoliths2": {
    #     "display_name": "Two-Way Monoliths",
    #     "filter": {objects.ID.Two_Way_MonolithPortal},
    #     "subfilter": groups.TWO_WAY_MONOLITHS,
    # },
    # "portals2": {
    #     "display_name": "Two-Way Portals",
    #     "filter": {objects.ID.Two_Way_MonolithPortal},
    #     "subfilter": groups.TWO_WAY_PORTALS,
    # },
    # "portals2_sea": {
    #     "display_name": "Two-Way Sea Portals",
    #     "filter": {objects.ID.Two_Way_MonolithPortal},
    #     "subfilter": groups.TWO_WAY_SEA_PORTALS,
    # },
    # "whirlpools": {"display_name": "Whirlpools", "filter": {objects.ID.Whirlpool}, "subfilter": None},
    # "junkmen": {
    #     "display_name": "Junkmen",
    #     "filter": {objects.ID.HotA_Visitable_1},
    #     "subfilter": {objects.SubID.HotAVisitable1.Junkman},
    # },
    # "dwellings": {
    #     "display_name": "Dwellings",
    #     "filter": {
    #         objects.ID.Creature_Dwelling_Normal,
    #         objects.ID.Creature_Dwelling_2,
    #         objects.ID.Creature_Dwelling_3,
    #         objects.ID.Creature_Dwelling_Multi,
    #         objects.ID.Random_Dwelling,
    #         objects.ID.Random_Dwelling_Leveled,
    #         objects.ID.Random_Dwelling_Faction,
    #     },
    #     "subfilter": None,
    # },
    # "prisons": {"display_name": "Prisons", "filter": {objects.ID.Prison}, "subfilter": None},
    # "monsters": {"display_name": "Monsters", "filter": groups.MONSTERS, "subfilter": None},
    # "spellscrolls": {"display_name": "Spell Scrolls", "filter": {objects.ID.Spell_Scroll}, "subfilter": None},
    # "shrine1": {
    #     "display_name": "Shrine Level 1",
    #     "filter": {objects.ID.Shrine_1_and_4},
    #     "subfilter": {objects.SubID.Shrine_1_and_4.Shrine_of_Magic_Incantation},
    # },
    # "shrine2": {
    #     "display_name": "Shrine Level 2",
    #     "filter": {objects.ID.Shrine_of_Magic_Gesture},
    #     "subfilter": None,
    # },
    # "shrine3": {
    #     "display_name": "Shrine Level 3",
    #     "filter": {objects.ID.Shrine_of_Magic_Thought},
    #     "subfilter": None,
    # },
    # "shrine4": {
    #     "display_name": "Shrine Level 4",
    #     "filter": {objects.ID.Shrine_1_and_4},
    #     "subfilter": {objects.SubID.Shrine_1_and_4.Shrine_of_Magic_Mystery},
    # },
    # "pyramids": {"display_name": "Pyramids", "filter": {objects.ID.Pyramid}, "subfilter": None},
    # "artifacts": {"display_name": "Artifacts", "filter": {objects.ID.Artifact}, "subfilter": None},
    # "randomartifacts": {"display_name": "Random Artifacts", "filter": {objects.ID.Random_Artifact}, "subfilter": None},
    # "randomtreasureartifacts": {
    #     "display_name": "Random Treasure Artifacts",
    #     "filter": {objects.ID.Random_Treasure_Artifact},
    #     "subfilter": None,
    # },
    # "randomminorartifacts": {
    #     "display_name": "Random Minor Artifacts",
    #     "filter": {objects.ID.Random_Minor_Artifact},
    #     "subfilter": None,
    # },
    # "randommajorartifacts": {
    #     "display_name": "Random Major Artifacts",
    #     "filter": {objects.ID.Random_Major_Artifact},
    #     "subfilter": None,
    # },
    # "randomrelics": {"display_name": "Random Relics", "filter": {objects.ID.Random_Relic}, "subfilter": None},
    # "resources": {"display_name": "Resources", "filter": groups.RESOURCES, "subfilter": None},
    # "treasurechests": {"display_name": "Treasure Chests", "filter": {objects.ID.Treasure_Chest}, "subfilter": None},
    # "scholars": {"display_name": "Scholars", "filter": {objects.ID.Scholar}, "subfilter": None},
    # "eventobjects": {"display_name": "Event Objects", "filter": {objects.ID.Event_Object}, "subfilter": None},
    # "tradingposts": {"display_name": "Trading Posts", "filter": groups.TRADING_POSTS, "subfilter": None},
    # "warlockslabs": {
    #     "display_name": "Warlock's Labs",
    #     "filter": {objects.ID.HotA_Visitable_1},
    #     "subfilter": {objects.SubID.HotAVisitable1.Warlocks_Lab},
    # },
    # "redwoodobservatories": {
    #     "display_name": "Redwood Observatories & Pillars of Fire",
    #     "filter": {objects.ID.Redwood_Observatory, objects.ID.Pillar_of_Fire},
    #     "subfilter": {objects.SubID.Observation.Redwood_Observatory},
    # },
    # "observationtowers": {
    #     "display_name": "Observation Towers",
    #     "filter": {objects.ID.Redwood_Observatory},
    #     "subfilter": {objects.SubID.Observation.Observation_Tower},
    # },
    # "observatories": {
    #     "display_name": "Observatories",
    #     "filter": {objects.ID.HotA_Visitable_2},
    #     "subfilter": {objects.SubID.HotAVisitable2.Observatory},
    # },
    # "coversofdarkness": {
    #     "display_name": "Covers of Darkness",
    #     "filter": {objects.ID.Cover_of_Darkness},
    #     "subfilter": None,
    # },
    # "oceanbottles": {"display_name": "Ocean Bottles", "filter": {objects.ID.Ocean_Bottle}, "subfilter": None},
    # "vialsofmana": {
    #     "display_name": "Vials of Mana",
    #     "filter": {objects.ID.HotA_Pickup},
    #     "subfilter": {objects.SubID.HotAPickups.Vial_of_Mana},
    # },
    # "obelisks": {
    #     "display_name": "Obelisks",
    #     "filter": {objects.ID.Obelisk},
    #     "subfilter": None,
    # },
    # "towngates": {
    #     "display_name": "Town Gates",
    #     "filter": {objects.ID.HotA_Visitable_2},
    #     "subfilter": {objects.SubID.HotAVisitable2.Town_Gate},
    # },
    # "primaryskillobjects": {
    #     "display_name": "Primary Skill Objects",
    #     "combofilter": [
    #         (objects.ID.Mercenary_Camp, {0}),
    #         (objects.ID.Marletto_Tower, {0}),
    #         (objects.ID.Star_Axis, {0}),
    #         (objects.ID.Garden_of_Revelation, {0}),
    #         (objects.ID.School_of_War, {0}),
    #         (objects.ID.School_of_Magic, {0}),
    #         (objects.ID.Arena, {0}),
    #         (objects.ID.HotA_Visitable_1, {objects.SubID.HotAVisitable1.Colosseum_of_the_Magi}),
    #         (objects.ID.Library_of_Enlightenment, {0}),
    #     ],
    # },
    # "mercenarycamps": {
    #     "display_name": "Mercenary Camps",
    #     "filter": {objects.ID.Mercenary_Camp},
    #     "subfilter": None,
    # },
    # "marlettotowers": {
    #     "display_name": "Marletto Towers",
    #     "filter": {objects.ID.Marletto_Tower},
    #     "subfilter": None,
    # },
    # "staraxis": {
    #     "display_name": "Star Axis",
    #     "filter": {objects.ID.Star_Axis},
    #     "subfilter": None,
    # },
    # "gardensofrevelation": {
    #     "display_name": "Gardens of Revelation",
    #     "filter": {objects.ID.Garden_of_Revelation},
    #     "subfilter": None,
    # },
    # "schoolsofwar": {
    #     "display_name": "Schools of War",
    #     "filter": {objects.ID.School_of_War},
    #     "subfilter": None,
    # },
    # "schoolsofmagicland": {
    #     "display_name": "Schools of Magic - Land",
    #     "filter": {objects.ID.School_of_Magic},
    #     "subfilter": {0},
    # },
    # "schoolsofmagicsea": {
    #     "display_name": "Schools of Magic - Sea",
    #     "filter": {objects.ID.School_of_Magic},
    #     "subfilter": {1},
    # },
    # "arenas": {
    #     "display_name": "Arenas",
    #     "filter": {objects.ID.Arena},
    #     "subfilter": None,
    # },
    # "colosseumsofthemagi": {
    #     "display_name": "Colosseums of the Magi",
    #     "filter": {objects.ID.HotA_Visitable_1},
    #     "subfilter": {objects.SubID.HotAVisitable1.Colosseum_of_the_Magi},
    # },
    # "librariesofenlightenment": {
    #     "display_name": "Libraries of Enlightenment",
    #     "filter": {objects.ID.Library_of_Enlightenment},
    #     "subfilter": None,
    # },
    # "denofthieves": {
    #     "display_name": "Dens of Thieves",
    #     "filter": {objects.ID.Den_of_Thieves},
    #     "subfilter": None,
    # },
    # "taverns": {
    #     "display_name": "Taverns",
    #     "filter": {objects.ID.Tavern},
    #     "subfilter": None,
    # },
}
